## ##YAML Template
default: --profile progress --profile html_report --profile one_tag --profile chrome --profile homolog
html_report: --format html --out=features_report.html
one_tag: -t @mapeando_lista_elementos
progress: --format progress
pretty: --format pretty
homolog: ENVIRONMENT=homolog
prod: ENVIRONMENT=prod
chrome: BROWSER=chrome
firefox: BROWSER=firefox
safari: BROWSER=safari